  name: Maven Build for Java 8, 11 and 15 on Ubuntu, mac, and windows
  on:
    push:
  jobs:
    build:
      name: "Build (JDK-${{ matrix.java }} ,${{ matrix.os }})"
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
          java: [8, 11, 15]
      runs-on: ${{ matrix.os }}
      steps:
        - name: 'Checkout'
          uses: actions/checkout@v2

        - name: 'Set up JDK'
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}

        - name: Cache Maven Dependencies
          uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: $ {{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

        - name: Build and test with Maven using xvfb
          uses: GabrielBB/xvfb-action@v1
          with:
            run: |
              mvn clean verify